<a href="https://colab.research.google.com/github/darko-jr/Intro-to-AI-Group5-Final-Project/blob/main/Sprint_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
RANDOM_STATE = 42

In [25]:
from google.colab import files
uploaded = files.upload()

Saving student-mat.csv to student-mat (1).csv

In [26]:
# Load dataset
mat = pd.read_csv("student-mat.csv", sep=";")

In [27]:
# Exporing the dataset
mat.shape
mat.head()
mat.info()
mat.describe()
mat.isna().sum()
mat.isnull().sum()
mat.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

np.int64(0)

In [28]:
# Creating a new column called risk level for the prediction
def risk_level(g1):
    if g1 <= 9:
        return "High"
    elif g1 <= 14:
        return "Medium"
    else:
        return "Low"

mat["Risk_level"] = mat["G1"].apply(risk_level)

In [29]:
mat.head()
mat.info()
mat.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
 33  Risk_level  395 non-null    object
dtypes: int64(16), object(18)
memory usage: 105.1+ KB

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [30]:
# Seperating and Targeting
X = mat.drop(['G1', 'Risk_level'], axis=1)
y = mat['Risk_level']

In [31]:
# Encoding the features

# Binary Encoding
encoder = LabelEncoder()

binary_features = [
    'school',
    'sex',
    'address',
    'famsize',
    'Pstatus',
    'schoolsup',
    'famsup',
    'paid',
    'activities',
    'nursery',
    'higher',
    'internet',
    'romantic'
]

for col in binary_features:
    X[col] = encoder.fit_transform(X[col])

binary_encoded_features = X[binary_features]


# OneHot Encoding
categorical_features = [
    'Mjob',
    'Fjob',
    'reason',
    'guardian'
]

enc = OneHotEncoder(
    drop='first',
    sparse_output=False
)

categorical_encoded = enc.fit_transform(
    X[categorical_features]
)

categorical_encoded_features = pd.DataFrame(
    categorical_encoded,
    columns=enc.get_feature_names_out(categorical_features),
    index=X.index
)


# StandardScaler Encoding

numeric_features = [
    'age',
    'Medu',
    'Fedu',
    'traveltime',
    'studytime',
    'failures',
    'famrel',
    'freetime',
    'goout',
    'Dalc',
    'Walc',
    'health',
    'absences'
]

scaler = StandardScaler()

scaled = scaler.fit_transform(
    X[numeric_features]
)

scaled_features = pd.DataFrame(
    scaled,
    columns=numeric_features,
    index=X.index
)

In [32]:
# Combining processed data

X_processed = pd.concat(
    [
        binary_encoded_features,
        categorical_encoded_features,
        scaled_features
    ],
    axis=1
)

In [33]:
# Splitting the data into 70, 15, 15

X_train, X_temp, y_train, y_temp = train_test_split(
    X_processed,
    y,
    test_size=0.30,
    random_state=RANDOM_STATE,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=RANDOM_STATE,
    stratify=y_temp
)

In [34]:
print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Testing:", X_test.shape)

X_processed.head()

Training: (276, 39)
Validation: (59, 39)
Testing: (60, 39)

,school,sex,address,famsize,Pstatus,schoolsup,famsup,paid,activities,nursery,...,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
0,0,0,1,0,0,1,0,0,0,1,...,0.792251,-0.042286,-0.449944,0.062194,-0.236010,0.801479,-0.540699,-1.003789,-0.399289,0.036424
1,0,0,1,0,1,0,1,0,0,0,...,-0.643249,-0.042286,-0.449944,1.178860,-0.236010,-0.097908,-0.540699,-1.003789,-0.399289,-0.213796
2,0,0,1,1,1,1,0,1,0,1,...,-0.643249,-0.042286,3.589323,0.062194,-0.236010,-0.997295,0.583385,0.551100,-0.399289,0.536865
3,0,0,1,0,1,0,1,1,1,1,...,-0.643249,1.150779,-0.449944,-1.054472,-1.238419,-0.997295,-0.540699,-1.003789,1.041070,-0.464016
4,0,0,1,0,1,0,1,1,0,1,...,-0.643249,-0.042286,-0.449944,0.062194,-0.236010,-0.997295,-0.540699,-0.226345,1.041070,-0.213796

In [35]:
# Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
lr_model = LogisticRegression(random_state=42, max_iter=1000)

# Train model
lr_model.fit(X_train, y_train)

# Validation predictions
y_val_pred_lr = lr_model.predict(X_val)

# Accuracy
lr_accuracy = accuracy_score(y_val, y_val_pred_lr)

print("Validation Accuracy:", lr_accuracy)

print("\nClassification Report")
print(classification_report(y_val, y_val_pred_lr))

print("\nConfusion Matrix")
print(confusion_matrix(y_val, y_val_pred_lr))

Validation Accuracy: 0.5254237288135594

Classification Report
              precision    recall  f1-score   support

        High       0.56      0.48      0.51        21
         Low       0.33      0.20      0.25        10
      Medium       0.54      0.68      0.60        28

    accuracy                           0.53        59
   macro avg       0.48      0.45      0.46        59
weighted avg       0.51      0.53      0.51        59


Confusion Matrix
[[10  0 11]
 [ 3  2  5]
 [ 5  4 19]]

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
dt_model = DecisionTreeClassifier(
    random_state=42,
    max_depth=5
)

# Train
dt_model.fit(X_train, y_train)

# Predict
y_val_pred_dt = dt_model.predict(X_val)

# Accuracy
dt_accuracy = accuracy_score(y_val, y_val_pred_dt)

print("Validation Accuracy:", dt_accuracy)

print("\nClassification Report")
print(classification_report(y_val, y_val_pred_dt))

print("\nConfusion Matrix")
print(confusion_matrix(y_val, y_val_pred_dt))

Validation Accuracy: 0.5084745762711864

Classification Report
              precision    recall  f1-score   support

        High       0.48      0.52      0.50        21
         Low       0.00      0.00      0.00        10
      Medium       0.54      0.68      0.60        28

    accuracy                           0.51        59
   macro avg       0.34      0.40      0.37        59
weighted avg       0.43      0.51      0.46        59


Confusion Matrix
[[11  0 10]
 [ 4  0  6]
 [ 8  1 19]]

In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train
rf_model.fit(X_train, y_train)

# Predict
y_val_pred_rf = rf_model.predict(X_val)

# Accuracy
rf_accuracy = accuracy_score(y_val, y_val_pred_rf)

print("Validation Accuracy:", rf_accuracy)

print("\nClassification Report")
print(classification_report(y_val, y_val_pred_rf))

print("\nConfusion Matrix")
print(confusion_matrix(y_val, y_val_pred_rf))

Validation Accuracy: 0.5932203389830508

Classification Report
              precision    recall  f1-score   support

        High       0.56      0.48      0.51        21
         Low       1.00      0.10      0.18        10
      Medium       0.60      0.86      0.71        28

    accuracy                           0.59        59
   macro avg       0.72      0.48      0.47        59
weighted avg       0.65      0.59      0.55        59


Confusion Matrix
[[10  0 11]
 [ 4  1  5]
 [ 4  0 24]]

In [38]:
results = {
    "Logistic Regression": lr_accuracy,
    "Decision Tree": dt_accuracy,
    "Random Forest": rf_accuracy
}

for model, score in results.items():
    print(f"{model}: {score:.4f}")

Logistic Regression: 0.5254
Decision Tree: 0.5085
Random Forest: 0.5932

In [39]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_val, y_val_pred_lr),
        accuracy_score(y_val, y_val_pred_dt),
        accuracy_score(y_val, y_val_pred_rf)
    ],
    "Precision": [
        precision_score(y_val, y_val_pred_lr, average="weighted"),
        precision_score(y_val, y_val_pred_dt, average="weighted"),
        precision_score(y_val, y_val_pred_rf, average="weighted")
    ],
    "Recall": [
        recall_score(y_val, y_val_pred_lr, average="weighted"),
        recall_score(y_val, y_val_pred_dt, average="weighted"),
        recall_score(y_val, y_val_pred_rf, average="weighted")
    ],
    "F1-Score": [
        f1_score(y_val, y_val_pred_lr, average="weighted"),
        f1_score(y_val, y_val_pred_dt, average="weighted"),
        f1_score(y_val, y_val_pred_rf, average="weighted")
    ]
})

print(comparison.sort_values(by="Accuracy", ascending=False))

                 Model  Accuracy  Precision    Recall  F1-Score
2        Random Forest  0.593220   0.651977  0.593220  0.548341
0  Logistic Regression  0.525424   0.511864  0.525424  0.511155
1        Decision Tree  0.508475   0.427856  0.508475  0.464218